### ISSUE TITLE
WebWallet Conformance: Brave Browser

### ISSUE THREAD

**Issue by okalouti** [omgnetwork/web-wallet#54]

**Comment by nicholasmueller** [comment]
Testing Brave's built in "Crypto Wallet".
Transactions without message works (deposit/exit), but not with the message. Brave's pop up is broken and you can't actually confirm the transaction.

Nothing we can do on our side to fix that. 

![Screen Shot 2020-05-12 at 12 54 07 (2)](https://user-images.githubusercontent.com/29919550/81643786-8a7d8d80-9450-11ea-8fcf-feb3963ca451.png)

**Comment by nicholasmueller** [comment]
Brave mobile does not have the crypto wallet feature

**Comment by nicholasmueller** [comment]
https://github.com/brave/brave-browser/issues/9775
