### ISSUE TITLE
Feature request: show "webwallet is syncing" while it's still syncing to the latest block

### ISSUE THREAD

**Issue by unnawut** [omgnetwork/web-wallet#67]
As a user I want to know whether the webwallet/watcher is still syncing or it's already up-to-date with latest block, so that I know whether I can create new transactions or I should wait while they're syncing.

Even better maybe, disable merge/transfer/exit while it's syncing.

-----

Some context:

We just nuked and watcher_info is resyncing with the childchain/rootchain. Very cool that the webwallet is auto-updating itself with the current sync.

One remaining confusion is that the user can't tell apart if the webwallet is up-to-date and this is the latest balances and transactions they can transact on, or if is still syncing (more data is being populated) and they should hold off creating new transactions.

This is shown around the time of resync, while there are a few more transactions already happened in May
![image](https://user-images.githubusercontent.com/921194/83390691-8a075f80-a41c-11ea-9254-a9f4e607dad8.png)

**Comment by nicholasmueller** [comment]
@unnawut  would that just be a check of the `eth_syncing` flag on `status.get`? current code hasnt been updated to use that status flag yet, its currently just comparing current eth block height to what the watcher has `last_seen` to give it the 'sync' status

**Comment by unnawut** [comment]
Hmm looks like both `eth_syncing` and `last_seen` will only catch when geth/infura is behind root chain but not when watcher is behind child chain. 

For now we probably need to compare `last_seen_eth_block_number - services_synced_heights.block_getter.height` and if it's > 20, it's considered syncing (technically it's 10 blocks but a number too low might flip the status too often)

I'll also file a ticket to `elixir-omg` and see if we could get `watcher_syncing: true/false` in

**Comment by unnawut** [comment]
loveeeeeeeeeeeeeeeee
