### ISSUE TITLE
Feature: walletconnect/link

### ISSUE THREAD

**Issue by nicholasmueller** [omgnetwork/web-wallet#69]
Be able to sign transactions in browsers without a web3 extension or built in crypto wallet using walletconnect/link.

https://docs.walletconnect.org/
https://www.walletlink.org/#/

TODOs for tracking:
- [x] prompt on boot for user to select provider (injected vs walletconnect vs walletlink)
- [x] walletconnect/link to connect through custom rpc/mw proxy to avoid distributing infura key https://docs.walletconnect.org/quick-start/dapps/web3-provider#custom-rpc-url
- [x] walletconnect is making ~60 rpc requests/min, this is way beyond our rate-limit. probably the binding of too many event listeners within walletconnect. to investigate.
- [x] walletconnect qr code api has a bug issued here -> https://github.com/WalletConnect/walletconnect-monorepo/issues/287 , investigate a workaround

wip branch => https://github.com/omgnetwork/web-wallet/tree/69-walletconnect

**Comment by pedrouid** [comment]
I just fixed the bug reported on WalletConnect/walletconnect-monorepo#287 👌 Thanks for reporting!

I believe there is pollingInterval that can be increased on the web3-provider engine that could bring down to your rate-limit

```js
const provider = new WalletConnectProvider({
      rpc: { 1: config.rpcProxy }
      pollingInterval: 10000 // 10 secs (default is 4 secs)
})
```

Could you try testing this in your integration?

**Comment by nicholasmueller** [comment]
@pedrouid thanks for the quick reply. qr code bug fixed and configuring the pollingInterval does bring the requests down. 👍 Thanks a lot!
