### ISSUE TITLE
Reduce infura calls

### ISSUE THREAD

**Issue by nicholasmueller** [omgnetwork/web-wallet#74]
- we make about 6 node calls every 15 seconds per client.
- we get this for free through a provider like metamask, but through dapp browser providers (imToken, status) we get timeouts, probably due to some kind of rate limiting.
- see what can be done to reduce these calls on the frontend, and make them only when needed (pending transactions, increase the interval when checking challenge period, etc)

**Comment by bg1156** [comment]
Go nic, Go!
